name: Actions Workflow
# GitHub Actions are written in JS 

on: [push]

jobs:
  Run-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
  # Instead of "run: attribute, we use "uses:" to indicate that we are running a GH Action with JS."
      - name: step-1 Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Christos
  # This action is published on an official JS repo and so we have to simply reference it.
  # When referencing a public GH repo as Action, we should use the format 'username/repo@'and then one of the following: 
  # 1) A branch (master or some other)
  # 2) The version
  # 3) A specific commit made in this repo 
  # We choose option 2 here, to be less restrive. For prod env it's reccomended to use option 3.
      - name: step-2 Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
  # As per documentation of this public GH repo, we can use the time as outputs from this action.
  # "greet" represents the added "id" attribute of step-1 to then reference it as variable in step-2.
      - name: step-3 List Files
        run: |
          pwd
          ls -a
  # By default GH will NOT clone your repo in the VM working Directory. 
  # To clone it, we used an official GH action in step-3.
      - name: step-4 Checkout Action
        uses: actions/checkout@v1
      - name: step-5 List Files after Checkout
        run: |
          pwd
          ls -a
  #


