name: Shell Commands

on: [push]

jobs: 
  Run-Shell-Command-job-1:
# Job 1 has 3 consequetive steps. Job 1 also has a dependancy on job 2 using the attribute "needs:". 
    runs-on: ubuntu-latest
    needs: ["Run-Windows-Command-job-2"]
    steps:
      - name: step-1 echo a string
        run: echo "Hello world"
      - name: step-2 multiline script
        run: | 
          node -v
          npm -v
      - name: step-3 Python command
        run: | 
          import platform
          print(platform.processor())
        shell: python
  
  Run-Windows-Command-job-2:
  # Job 2 is running on Windoows and has 2 consequetive steps. It is printing the current directory in both Bash and PowerShell.
    runs-on: windows-latest
    steps:
      - name: step-1 Directory PowerShell
        run: get-location
      - name: step-2 Directory Bash
        run: pwd
        shell: bash








