name: Shell Commands

on: [push]

jobs: 
  Run-Shell-Command-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1 echo a string
        run: echo "Hello world"
      - name: step-2 multiline script
        run: | 
          node -v
          npm -v








