name: Shell Commands

on: [push]

jobs: 
  Run-Shell-Command-job-1:
    runs-on: ubuntu-latest
    needs: ["Run-Windows-Command-job-2"]
    steps:
      - name: step-1 echo a string
        run: echo "Hello world"
      - name: step-2 multiline script
        run: | 
          node -v
          npm -v
      - name: step-3 Python command
        run: | 
          import platform
          print(platform.processor())
        shell: python
  
  Run-Windows-Command-job-2:
    runs-on: windows-latest
    steps:
      - name: step-1 Directory PowerShell
        run: get-location
      - name: step-2 Directory Bash
        run: pwd
        shell: bash








